# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29420e31e156d439c72f25ef88d87abf7ad6c2410b0323651221ea9af4c388309dffcc5f17888e83b14d53724362a4899a30edfbdf6ab34955517bb032b94bac

test:
  secret_key_base: 0e297da6a8d70ea281e7adf8ea478b8d8e8920c91e3b670eb89daa60a1b61f129d61d65d4322c53f88a48642271ed5304cb5145e9677b3cd92cab303fd550bee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
